name: Format
on: [push, pull_request, workflow_dispatch]

jobs:
  run:
    name: Format
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ github.token }}

      - name: Setup Node.JS
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
          cache: "npm"

      - name: Install
        run: npm install

      - name: Prettier
        run: npm run fmt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: "Format code using Prettier"
          branch: ${{ github.head_ref }}
